services:
  - type: web
    name: n8n-server
    env: image
    image:
      url: docker.n8n.io/n8nio/n8n:latest
    plan: free # Cambiar a 'starter' ($7/mes) si quieres usar cronjobs y que no se duerma
    healthCheckPath: /healthz
    envVars:
      # Configuracion de Base de Datos PostgreSQL
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_DATABASE
        value: n8n
      - key: DB_POSTGRESDB_USER
        value: n8n
      - key: DB_POSTGRESDB_PASSWORD
        fromDatabase:
          name: n8n-db
          property: password
      - key: DB_POSTGRESDB_HOST
        fromDatabase:
          name: n8n-db
          property: host
      - key: DB_POSTGRESDB_PORT
        fromDatabase:
          name: n8n-db
          property: port
          
      # Configuracion de N8N
      - key: N8N_HOST
        value: automation.marcoslozina.com
      - key: N8N_PORT
        value: 5678
      - key: N8N_PROTOCOL
        value: https
      - key: NODE_ENV
        value: production
      - key: WEBHOOK_URL
        value: https://automation.marcoslozina.com/
        
      # Seguridad (Basic Auth)
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        sync: false # Render te pedira que ingreses este valor manual en su panel web
      - key: N8N_BASIC_AUTH_PASSWORD
        sync: false # Al igual que este
      - key: N8N_ENCRYPTION_KEY
        generateValue: true # Render generara una clave encriptada segura automaticamente

# Base de datos PostgreSQL para n8n
databases:
  - name: n8n-db
    databaseName: n8n
    user: n8n
    plan: free # ATENCION: Las bases de datos Free de Render se ELIMINAN a los 90 dias
